// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendPath(arg1:string,arg2:string):Promise<string>;

export function DirExists(arg1:string):Promise<boolean>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetError():Promise<string>;

export function GetOSName():Promise<string>;

export function MakeDir(arg1:string):Promise<void>;

export function MakeFile(arg1:string):Promise<void>;

export function MoveEntries(arg1:string,arg2:string):Promise<void>;

export function OpenExcelFile(arg1:string):Promise<Array<string>>;

export function OpenFile(arg1:string):Promise<string>;

export function Quit():Promise<void>;

export function ReadDir(arg1:string):Promise<Array<main.FileInfo>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileB(arg1:string):Promise<Array<number>>;

export function RenameEntry(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SplitFile(arg1:string):Promise<main.FileParts>;

export function StartFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<string>;
