// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendPath(arg1, arg2) {
  return window['go']['main']['App']['AppendPath'](arg1, arg2);
}

export function DirExists(arg1) {
  return window['go']['main']['App']['DirExists'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetError() {
  return window['go']['main']['App']['GetError']();
}

export function GetOSName() {
  return window['go']['main']['App']['GetOSName']();
}

export function MakeDir(arg1) {
  return window['go']['main']['App']['MakeDir'](arg1);
}

export function MakeFile(arg1) {
  return window['go']['main']['App']['MakeFile'](arg1);
}

export function MoveEntries(arg1, arg2) {
  return window['go']['main']['App']['MoveEntries'](arg1, arg2);
}

export function OpenExcelFile(arg1) {
  return window['go']['main']['App']['OpenExcelFile'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileB(arg1) {
  return window['go']['main']['App']['ReadFileB'](arg1);
}

export function RenameEntry(arg1, arg2) {
  return window['go']['main']['App']['RenameEntry'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SplitFile(arg1) {
  return window['go']['main']['App']['SplitFile'](arg1);
}

export function StartFile(arg1) {
  return window['go']['main']['App']['StartFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
